---
all:
  children:
    pcs_servers:
       hosts:
         pcs1:
           ansible_host: "192.168.56.201"
           ansible_private_key_file: ".vagrant/machines/pcs1/virtualbox/private_key"
         pcs2:
           ansible_host: "192.168.56.202"
           ansible_private_key_file: ".vagrant/machines/pcs2/virtualbox/private_key"
         pcs3:
           ansible_host: "192.168.56.203"
           ansible_private_key_file: ".vagrant/machines/pcs3/virtualbox/private_key"
       vars:
         virtualbox_host: "192.168.56.1"
         virtualbox_host_username: "mbfx"
         virtualbox_host_password: "strong_pass"
  vars:
    domain: "mydomain.test"
    ntp_timezone: "UTC"
    pcs_password: "strong_pass" # cluster user: hacluster
    cluster_name: "hacluster"
...
