# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
    ns02.vm.hostname = "ns02"
  end

  config.vm.define "client1" do |client1|
    client1.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net1"
    client1.vm.hostname = "client1"
  end

  config.vm.define "client2" do |client2|
    client2.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net1"
    client2.vm.hostname = "client2"
  end

  config.vm.define "relay" do |relay|
    relay.vm.network "private_network", ip: "192.168.50.200", virtualbox__intnet: "net1"
    relay.vm.network "private_network", ip: "192.168.60.10", virtualbox__intnet: "net2"
    relay.vm.hostname = "relay"
  end

  config.vm.define "client3" do |client3|
    client3.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net2"
    client3.vm.hostname = "client3"
  end

end
